spring:
  datasource:
    url: jdbc:mysql://localhost:3306/portfolio_db
    username: root
    password: Ferid123+

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true


